server:
  port: 9099
spring:
  application:
    name: less-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:  # 路由
          - id: less-blog #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
            uri: http://localhost:9100 # 匹配提供服务的路由地址
            predicates: # 断言
              - Path=/blog/** # 断言，路径相匹配进行路由
            filters:
              - StripPrefix= 1
  main:
    web-application-type: reactive